import Head from "next/head";
import React from "react";
import AddTodo from "../components/addTodo";
import Contact_form from "../components/Contact_form";
import Hero from "../components/Hero";
import Footer from "../components/Footer";

const Contact = () => {
  return (
    <div>
      <Head>
        <title>Photography Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero
        heading="Contact"
        message="Submit the form below for more work quotes"
      />
      {/* <Contact_form /> */}
      <AddTodo />
      <Footer />
    </div>
  );
};

export default Contact;
